name: PR-comment

on: pull_request

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'You should expect an initial response to your PR from the team within 7 days. Note that this response may be delayed during holiday periods.' });'